{% set version = "2.1-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatialextremes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SpatialExtremes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SpatialExtremes/SpatialExtremes_{{ version }}.tar.gz
  sha256: 438694a02f4354ccd740675936cb409d9fd634e95d66357583e87b1d6ee73a7c

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fields
    - r-maps
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-fields
    - r-maps

test:
  commands:
    - $R -e "library('SpatialExtremes')"           # [not win]
    - "\"%R%\" -e \"library('SpatialExtremes')\""  # [win]

about:
  home: http://spatialextremes.r-forge.r-project.org/
  license: GPL-2.0-or-later
  summary: 'Tools for the statistical modelling of spatial extremes using max-stable processes, copula or Bayesian hierarchical models. More precisely, this package allows (conditional) simulations from various parametric max-stable models, analysis of the extremal spatial dependence, the fitting of such processes using
    composite likelihoods or least square (simple max-stable processes only), model checking and selection and prediction. Other approaches (although not completely in agreement with the extreme value theory) are available such as the use of (spatial) copula and Bayesian hierarchical models assuming the so-called conditional
    assumptions. The latter approaches is handled through an (efficient) Gibbs sampler. Some key references: Davison et al. (2012) <doi:10.1214/11-STS376>, Padoan et al. (2010) <doi:10.1198/jasa.2009.tm08577>, Dombry et al. (2013) <doi:10.1093/biomet/ass067>.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: SpatialExtremes
# Version: 2.0-7.2
# Date: 2018-07-02
# Title: Modelling Spatial Extremes
# Authors@R: c(person("Mathieu", "Ribatet", role = c("aut", "cre"), email = "mathieu.ribatet@umontpellier.fr"), person("Richard", "Singleton", role = "ctb"), person("R Core team", role = "ctb"))
# Depends: R (>= 1.8.0)
# Imports: maps, fields
# Description: Tools for the statistical modelling of spatial extremes using max-stable processes, copula or Bayesian hierarchical models. More precisely, this package allows (conditional) simulations from various parametric max-stable models, analysis of the extremal spatial dependence, the fitting of such processes using composite likelihoods or least square (simple max-stable processes only), model checking and selection and prediction. Other approaches (although not completely in agreement with the extreme value theory) are available such as the use of (spatial) copula and Bayesian hierarchical models assuming the so-called conditional assumptions. The latter approaches is handled through an (efficient) Gibbs sampler. Some key references: Davison et al. (2012) <doi:10.1214/11-STS376>, Padoan et al. (2010) <doi:10.1198/jasa.2009.tm08577>, Dombry et al. (2013) <doi:10.1093/biomet/ass067>.
# License: GPL (>= 2)
# URL: http://spatialextremes.r-forge.r-project.org/
# NeedsCompilation: yes
# Packaged: 2019-08-02 14:41:39 UTC; ripley
# Author: Mathieu Ribatet [aut, cre], Richard Singleton [ctb], R Core team [ctb]
# Maintainer: Mathieu Ribatet <mathieu.ribatet@umontpellier.fr>
# Repository: CRAN
# Date/Publication: 2019-08-02 15:08:41 UTC
