travis:
  secure:
    BINSTAR_TOKEN: Y9eckmuzzkHYGwuJuOfK36B/gmS7TT5lRqw14PWqwE38JOjakL4VUW3INTp1Zp3DqcZQhLx/aNRPO2w7d9gWAjoSbWPFXVB8f+poqTNt1V97OwljjlyDfTeumyWkgmXjduPrtzHNC83seJ7dwgtSdtVmrcGreTGFbQLBChyofUbl/kcbX5vBRz2nIkrJR1NYp+gxyqU5UQXWgZhGnWKRpYJ+V1HJ3Zee2iDIQ2Is4DN56MLouSxCp/9OszfHyinmTF41lqLTjMDwXKuHVI+h3M8uxGp1QlGkTyiehEpZwI2mZ2vTGMZPqbaJIjj0j2XcbbKfUWE3Y5PK5r4ujcPhihmXwZwDsTiBE84B+sLVXHZ/O3M0Dikk72ngtvUyo0kJw5mjtFF7+5kjpEZ6RCUED47wtZ1ou7zNJUv1SVJaCutcLcLmn5dkXL3crdZW8MYa8WUusQAeVcqh6k//1QPi5u6hQErFhAQPQAIIvx68lJHxVJwEtQ0aWKf/jojVQE5QX1oLcFbD1tmAtLi0JPGPvj7YzUte/0vhHqtjcibFppzNVSm/ogoq5TmMJrRWU6lOCdlY2WYIsuIuLtEPdoxMXUgdE09kkAFH70wVHIP0PRKukJKo6DB3IycZU6V0Vu/ZSXSolJwwVNmSHGP93a9HrlpybiL9tPjlWlBysh6cn4s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
