travis:
  secure:
    BINSTAR_TOKEN: V5vzd9uR2znLnGmI4hALSJUvsLRjb2Hm6nguzApx5PFMuxFNKG3K6vJxKa+HZ8Vm3G2ltKVVtUE+CPRgkDaYheuPWZ29kGiBOkTWHZ6M1xpxZ+3sYonLzAKkzZe7ixrXd73q0ZJQ+E8+rvyX3VkmfgLsSpQjilTL7dBCQ51P/JBwZUJZOb4f6AhdJRoEFY6ZxvAPepAcKVauH/W9khLJaK3M9xcoxnIzCctqKL36fg6P63BPJgSYWmCimmVjR9Jof4Ms2tgdV3az0e06axS5FssXGU6KP9v0tpoGNXmIUE/4xGMzxA1QmtrlnC/4zh8f8ZtAAkLIQQWCygVysmfalUm5zCJ72gymFRsmzDtWtNWyqjJHn3HSrqho4lUf7MijigryO8sxdtRvQduw7PZmKY5RWpOid2IIWN+dcehRB19J2k9rUkjbPqpCv1GK0wC51nALIo4NtWZ02YyfrRxZb728kKvx9NDlMItUhMP5hrHvHX5lmc5qQR/fh11oPUrLKZFjmtdIhZBusfuNinQ9pIoKU5CUHa8wM9ArSgJEC4eTUF3LZcqnYo+GoRigJ3j+CfnxokIfB5ExcIdnF9/rxSJTR12vGW+X5K2IMKD12vokylKVHbg231rmal2FSmX8e2ShU2sBGxSjaMAbSEqyaAvhDFF/5St3wcYOHz291UA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
